name: Bundle src folder
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r chrome-extension.zip src
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          release_name: "Release ${{ steps.vars.outputs.sha_short }}"
          draft: false
          prerelease: false
      - name: Upload zip file as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
          asset_path: chrome-extension.zip
          asset_name: chrome-extension.zip
          asset_content_type: application/zip
      - name: Add comment with download link
        run: |
          COMMENT="The src folder has been bundled into a zip file and uploaded as a release asset. You can download the file from the [release page](${{ steps.create_release.outputs.html_url }}) of this repository."
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            PAYLOAD="{\"body\": \"$COMMENT\"}"
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "$PAYLOAD" "
